### ISSUE TITLE
How to use

### ISSUE THREAD

**Issue by akamob** [Daniel-Jangua/gait-recognition#1]
Hi, Thank you for the great work.

I have a VLP-16 lidar and I want to use it for activity recognition, I convert my point clouds into RGB images and record as video files. I want to use your package to test these files.

Could you give me some suggestions to use your code? or is there any tutorials?

Any help is much appreciated:)

**Comment by Daniel-Jangua** [comment]
Hi! Thanks for your interest!

Right now I don't have any tutorial or something like that related to this code yet. But I'm working on a documentation to demonstrate how It has built and how to use it. I'll be putting it on README as soon as it is ready.

My code is focused on biometric recognition based on gait features. It implements the method presented [here](https://sol.sbc.org.br/journals/index.php/reic/article/view/2081), hope it helps you somehow while the documentation isn't ready.

Best regards!

**Comment by akamob** [comment]
Thank you very much for your reply.

I will try to understand your method and look forward to using your code:) if I got some new problems then would I contact you again?

Thank you!

**Comment by Daniel-Jangua** [comment]
Sure! Feel free to contact me if you need.

Here's my email daniel.jangua@unesp.br
